### ISSUE TITLE
Not published on NPM

### ISSUE THREAD

**Issue by g5becks** [joelek/atlas#1]
Hey, this looks like a really cool project. Looking to use this in an app and I tried to install it but it's not on npm. Are you planning to publish the package at any point?

Thanks.

**Comment by joelek** [comment]
> Hey, this looks like a really cool project. Looking to use this in an app and I tried to install it but it's not on npm. Are you planning to publish the package at any point?
> 
> Thanks.

Hi! Nice to hear that you are interested in the project.

The GitHub platform provides me with all the functionality I need to install and update my packages through npm. I haven't found a reason for publishing my packages on the npm registry so far.

Atlas may be installed through `npm install joelek/atlas#semver:^1.0` and subsequently updated as if it was installed via the npm registry.

Is there a specific reason for why you want to install the package via the npm registry?
